### ISSUE TITLE
nTweaks status

### ISSUE THREAD

**Issue by Slind14** [nallar/nTweaks#2]
Hey @nallar 
I was wondering what the current status of this project is. Is it abandoned, will it be continued. I would really like to use it in production mode as mobs/mobspawning seems to be quite heavy:

- 1270v3
- 16 players
- 8 tps
- 70-80% (90-100ms) mobs according to tickProfiler (mainly squid's and hostile)
- mobs are spread over the whole world (no big mob farm)

**Comment by nallar** [comment]
Not working on it much (you can tell by how long it took to notice this issue :P).

Occasionally making changes, and the existing patches should be fine for production use. Incompatible with some mods which have world leak issues, so you may need to turn off the world cleaning and world unloading patches if that's a problem.

**Comment by Slind14** [comment]
yeah, I noticed :D @nallar any chance on accepting the java patcher pull req and updating the maven repo + modpatcher depend? I would like to use the official repo.

**Comment by nallar** [comment]
I'm having some trouble building ModPatcher - Gradle's being unhappy, guessing something changed that conflicts with the [weird build.gradle](https://github.com/nallar/ModPatcher/blob/master/build.gradle#L112). Will need to get that sorted first.
